# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYZAIMDEHYtpGpdWJz97H8OCeF1J_y6S
"""

"""
2D-DCT Image Compression Implementation

Reference:
Y. Sampath Kumar et al.,
"2D-DCT based Dynamically Controllable Image Compression",
IEEE EPTC 2020.
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
import os

# ===============================
# 1. Load Image (Grayscale)
# ===============================
img = cv2.imread('Graceful dahlia in grayscale elegance.png', cv2.IMREAD_GRAYSCALE)
img = cv2.resize(img, (256, 256))  # standard size

# Convert to float
img = np.float32(img)

# ===============================
# 2. Define Block Size
# ===============================
block_size = 8

h, w = img.shape

# ===============================
# Function for 2D-DCT Compression
# ===============================
def dct_compress(original_img, threshold, block_size=8):
    h, w = original_img.shape
    reconstructed_img = np.zeros_like(original_img)

    for i in range(0, h, block_size):
        for j in range(0, w, block_size):
            block = original_img[i:i+block_size, j:j+block_size]
            dct = cv2.dct(block)
            dct[np.abs(dct) < threshold] = 0
            idct = cv2.idct(dct)
            reconstructed_img[i:i+block_size, j:j+block_size] = idct

    mse = np.mean((original_img - reconstructed_img) ** 2)
    if mse == 0:
        psnr = 100
    else:
        psnr = 10 * np.log10((255 ** 2) / mse)

    return reconstructed_img, psnr

# ===============================
# 3. Compression Parameters and Execution
# ===============================
thresholds = [5, 10, 20] # Example thresholds for low, medium, high compression

recon_low, psnr_low = dct_compress(img, thresholds[0], block_size)
recon_med, psnr_med = dct_compress(img, thresholds[1], block_size)
recon_high, psnr_high = dct_compress(img, thresholds[2], block_size)

# ===============================
# 5. Compute Metrics (for medium compression as in original single run)
# ===============================
print("MSE (medium compression):", np.mean((img - recon_med) ** 2))
print("PSNR (medium compression):", psnr_med)

# ===============================
# 6. Display Images
# ===============================
plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.title("Original Image")
plt.imshow(img, cmap='gray')

plt.subplot(1,2,2)
plt.title("Compressed Image (Medium Compression)")
plt.imshow(recon_med, cmap='gray')

plt.show()

# ===============================
# 7. Save Output and Comparison
# ===============================


os.makedirs('results', exist_ok=True)

cv2.imwrite('compressed_medium.jpg', recon_med)

plt.figure(figsize=(12,6))

plt.subplot(1,4,1)
plt.title("Original")
plt.imshow(img, cmap='gray')

plt.subplot(1,4,2)
plt.title("Low Compression")
plt.imshow(recon_low, cmap='gray')

plt.subplot(1,4,3)
plt.title("Medium")
plt.imshow(recon_med, cmap='gray')

plt.subplot(1,4,4)
plt.title("High")
plt.imshow(recon_high, cmap='gray')

plt.savefig("results/comparison.png")
plt.show()

psnr_values = [psnr_low, psnr_med, psnr_high]

plt.figure()
plt.plot(thresholds, psnr_values, marker='o')
plt.xlabel("Threshold (Compression Level)")
plt.ylabel("PSNR (dB)")
plt.title("PSNR vs Compression")
plt.grid()

plt.savefig("results/psnr_plot.png")
plt.show()

